---
# SPDX-PackageSummary: finnix-live-build
# SPDX-FileCopyrightText: © 2022 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: CC-BY-SA-4.0

title: "LOCALE-CONFIG(1) | locale-config"
author: "Ryan Finnie <ryan@finnie.org>"
