name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Cache live-build
      uses: actions/cache@v2
      with:
        path: build/cache
        key: finnix-live-build-1
    - name: Dependency packages
      run: |
        sudo apt update
        sudo apt -y install $(cat build-dependencies.txt)
    - name: Lint codebase
      run: env LINT=true ./finnix-live-build
    - name: Build image
      run: sudo env BUILD_TAGS="github ci" ./finnix-live-build
    - name: Post-build cleanup
      run: |
        sudo rm -rf build/cache/lb/bootstrap build/cache/lb/contents.chroot build/cache/lb/indices.bootstrap
