name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Dependency packages
      run: |
        sudo apt-get update
        sudo apt -y install build-essential debhelper devscripts po4a gettext man-db debian-archive-keyring librsvg2-bin fonts-liberation2 python3-jinja2 shellcheck
    - name: Build / install live-build
      run: |
        sudo rm -f /usr/bin/checkbashisms
        cd live-build
        debuild -us -uc
        sudo apt -y install ../*.deb
    - name: Build image
      run: sudo env LINT=true ./finnix-live-build
