name: release
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Dependency packages
      run: |
        sudo apt update
        sudo apt -y install $(tools/get-dependencies --only required)
        for pkg in $(tools/get-dependencies --only optional); do
          sudo apt -y install "${pkg}" || true
        done
    - name: Pre-build prepare
      run: |
        sudo chown -R root:root .
        env | grep ^GITHUB_ | sudo tee -a /etc/environment >/dev/null
    - name: Build image
      run: |
        sudo env BUILD_TAGS="release" ./finnix-live-build
    - name: Build source image
      run: |
        TEMP_DATA_DIR="$(sudo mktemp -d -p "$(pwd)/build")"
        sudo env SOURCE_ISO=true DATA_DIR="${TEMP_DATA_DIR?}" ./finnix-live-build
        sudo mv "${TEMP_DATA_DIR}/lb/finnix-source.iso" build/lb/
        sudo rm -rf "${TEMP_DATA_DIR?}"
        echo "Note: The build information listed above is not used; only the source ISO is saved."
        echo "See the 'Build image' step for actual build information."
    - name: Post-build cleanup
      run: |
        sudo chown -R "$(id -un):$(id -gn)" .
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: finnix-live-build.${{ github.workflow }}.${{ github.job }}.${{ github.run_number }}.${{ github.run_id }}
        path: |
          build/lb/finnix-*
          build/lb/chroot.files
          build/lb/chroot.packages.*
