name: schedule
on:
  schedule:
  - cron: '34 5 * * 1'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Dependency packages
      run: |
        sudo apt update
        sudo apt -y install build-essential debhelper devscripts po4a gettext man-db debian-archive-keyring librsvg2-bin fonts-liberation2 python3-jinja2
    - name: Build / install live-build
      run: |
        TMPBIN="$(mktemp -d)"
        ln -sf /bin/true "${TMPBIN}/checkbashisms"
        cd live-build
        dch --controlmaint --local "+git$(git show --pretty=format:"%cs.%h" --no-patch | sed 's/-//g')" ''
        debuild --prepend-path="${TMPBIN}" -b -us -uc
        sudo apt -y install --reinstall ../live-build_*.deb
    - name: Build image
      run: sudo ./finnix-live-build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: finnix-live-build.${{ github.workflow }}.${{ github.job }}.${{ github.run_number }}.${{ github.run_id }}
        path: build/lb/finnix-*
