name: schedule
on:
  schedule:
  - cron: '34 5 * * 1'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Dependency packages
      run: |
        sudo apt update
        sudo apt -y install debootstrap debian-archive-keyring apt-utils gzip bzip2 xz-utils cpio file coreutils rsync wget librsvg2-bin fonts-liberation2 python3-jinja2
    - name: Build image
      run: sudo ./finnix-live-build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: finnix-live-build.${{ github.workflow }}.${{ github.job }}.${{ github.run_number }}.${{ github.run_id }}
        path: build/lb/finnix-*
